repositoryUrl: https://github.com/dynamsoft-docs/capture-vision-docs-js/blob/main
repository: dynamsoft-docs/capture-vision-docs-js
docFullPath: https://www.dynamsoft.com/capture-vision/docs/web/
firstLevelUrl: /capture-vision/docs/web/
docRootName: "Dynamsoft Capture Vision JS Edition" 
docHomePage: /capture-vision/docs/core/introduction/

introduction: /capture-vision/docs/core/introduction/
architecture: /capture-vision/docs/core/architecture/
parameter: /capture-vision/docs/core/parameters/
parameterFile: /capture-vision/docs/core/parameters/file/
parameterReference: /capture-vision/docs/core/parameters/reference/
enums: /capture-vision/docs/core/enums/

js: /capture-vision/docs/web/programming/javascript/
dcv_js_api: /capture-vision/docs/web/programming/javascript/api-reference/
dbr_js_api: /barcode-reader/docs/web/programming/javascript/api-reference/
dlr_js_api: /label-recognition/docs/web/programming/javascript/api-reference/
ddn_js_api: /document-normalizer/docs/web/programming/javascript/api-reference/

assets: /capture-vision/docs/web/assets/
edit_icon: /capture-vision/docs/web/assets/img-icon/edit-icon.png
smile_icon: /capture-vision/docs/web/assets/img-icon/icon-smile.png
sad_icon: /capture-vision/docs/web/assets/img-icon/icon-sad.png
dbr_icon: /capture-vision/docs/web/assets/img-icon/icon-dbr.svg
dwt_icon: /capture-vision/docs/web/assets/img-icon/icon-dwt.svg
dnt_icon: /capture-vision/docs/web/assets/img-icon/icon-dnt.svg

useVersionTree: true

baseurl: "/capture-vision/docs/web"
plugins:
  - jemoji
  - jekyll-webp
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-seo-tag

url: "https://www.dynamsoft.com" # sitemap root

