repositoryUrl: https://github.com/dynamsoft-docs/capture-vision-docs-js/blob/main
repository: dynamsoft-docs/capture-vision-docs-js
docFullPath: https://www.dynamsoft.com/capture-vision/docs/web/
firstLevelUrl: /capture-vision/docs/web/
docRootName: "Dynamsoft Capture Vision JS Edition" 
docHomePage: /capture-vision/docs/web/programming/javascript/

dcvb_introduction: /capture-vision/docs/core/introduction/
dcvb_architecture: /capture-vision/docs/core/architecture/
dcvb_parameters: /capture-vision/docs/core/parameters/reference/
dcvb_parameter_file: /capture-vision/docs/core/parameters/file/
dcvb_enums: /capture-vision/docs/core/enums/
license_activation: /capture-vision/docs/core/license/

dcvb_js: /capture-vision/docs/web/programming/javascript/
dcvb_js_api: /capture-vision/docs/web/programming/javascript/api-reference/
dbr_js: /barcode-reader/docs/web/programming/javascript/
dlr_js: /label-recognition/docs/web/programming/javascript/
ddn_js: /document-normalizer/docs/web/programming/javascript/
dcp_js: /code-parser/docs/web/programming/javascript/
dce_js: /camera-enhancer/docs/web/programming/javascript/
dbr_js_api: /barcode-reader/docs/web/programming/javascript/api-reference/
dlr_js_api: /label-recognition/docs/web/programming/javascript/api-reference/
ddn_js_api: /document-normalizer/docs/web/programming/javascript/api-reference/
dcp_js_api: /code-parser/docs/web/programming/javascript/api-reference/
dce_js_api: /camera-enhancer/docs/web/programming/javascript/api-reference/
code_types: /code-parser/docs/core/code-types/
dcvb_root: /capture-vision/docs/core/

assets: /capture-vision/docs/web/assets/
edit_icon: /capture-vision/docs/web/assets/img-icon/edit-icon.png
smile_icon: /capture-vision/docs/web/assets/img-icon/icon-smile.png
sad_icon: /capture-vision/docs/web/assets/img-icon/icon-sad.png
dbr_icon: /capture-vision/docs/web/assets/img-icon/icon-dbr.svg
dwt_icon: /capture-vision/docs/web/assets/img-icon/icon-dwt.svg
dnt_icon: /capture-vision/docs/web/assets/img-icon/icon-dnt.svg

useVersionTree: true

baseurl: "/capture-vision/docs/web"
plugins:
  - jemoji
  - jekyll-webp
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-seo-tag

url: "https://www.dynamsoft.com" # sitemap root

